config/routes.rb
Rails.application.routes.draw do

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'places#home'

resources :places
resources :contacts
resources :users
get '/contato', to: 'contacts#new'
post '/contato', to: 'contacts#create'
get '/list', to: 'places#list'
get '/profissionaisvegs', to: 'professionals#profs'
get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  before_save :downcase_email
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :body
  validates :body,   length: { in: 1..2000 }

  def downcase_email
    self.email = email.downcase
  end

end

app/models/place.rb
class Place < ApplicationRecord

  scope :vegan, -> {where(:sort => "Vegano")}

  def self.search(search)
    if search
      if search != ''
        where('modality LIKE ? or address LIKE ?', "%#{search}%", "%#{search}%").order("RANDOM()")
      else
        where(name: 'Joei')
      end
    else
      where(name: 'Joet')
    end
  end

end

app/models/professional.rb
class Professional < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true
  validates :password, presence: true

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(message_params)
    if @contact.save
      ContactMailer.contact_me(@contact).deliver
      flash[:success] = "Formulário enviado com sucesso."
      redirect_to '/contato'
    else
      flash.now[:danger] = 'O formulário não pôde ser enviado. Verifique se os campos estão preenchidos corretamente.'
      render :new
    end
  end


private

  def message_params
    params.require(:contact).permit(:name, :email, :body)
  end
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  before_action :set_place, only: [:edit, :update, :destroy]
  before_action :logged_in_user, only: [:list]

  def home
  end

  def create
    @place = Place.create(place_params)
    if @place.save
      redirect_to list_url
    end
  end

  def index
    @places = Place.search(params[:search])
  end

  def edit
  end

  def update
    if @place.update(place_params)
      redirect_to list_url, notice: 'Estabelecimento atualizado'
    end
  end

  def list
    @place = Place.new
    @places = Place.all.order(:name)
  end

  def destroy
    @place.destroy
    redirect_to list_url, notice: 'Estabelecimento deletado'
  end

  private

  def place_params
    params.require(:place).permit(:name, :modality, :description, :openinghours, :address, :sort, :facebookpage, :search)
  end

  def set_place
    @place = Place.find(params[:id])
  end

  def logged_in_user
   unless logged_in?
     flash[:danger]= "You can not access this page"
      redirect_to root_url
    end
  end

end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController

  def profs
    @professionals = Professional.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      redirect_to list_path
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/places_helper.rb
module PlacesHelper

  def places_count
    Place.count
  end

  def search_count
    if @places.count > 0
      "Sua busca gerou " + pluralize(@places.count, "resultado")
    else
      "Nenhum estabelecimento foi encontrado"
    end
  end
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper

  def professionals_count
    Professional.count
  end    
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end


  def log_out
    session.delete(:user_id)
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/views/contacts/new.html.erb
<% provide(:title, "| Contato") %>

<div class="row">
  <div class="col-lg-6">
    <p id="contact" align="justify">Sinta-se a vontade em usar o espaço a seguir para fazer a recomendação de algum estabelecimento ou sugerir alguma correção.
    </p>
    <p id="contact" align="justify">Se você é
    profissional vegetariano(a) ou vegano(a) e a sua área de atuação é conectada ao vegetarianismo ou veganismo, indique-a juntamente com o local
    de atendimento ou trabalho.</p>
    <p id="contact" align="justify">Caso seja
    proprietário(a) de estabelecimento veg, você pode indicar uma pequena descrição (máximo 70 caracteres) para o seu empreendimento.</p>
    <p id="contact" align="justify">Contato: lucianocordeiro1991@hotmail.com</p>
  </div>

  <%= form_for(@contact) do |f| %>
    <%= notice %>
    <div class="col-lg-5 col-lg-offset-1">
      <ul class="form">
        <li><%= f.text_field :name, placeholder: 'Nome', size: "40x10" %></li>
        <li><%= f.email_field :email, placeholder: 'Email', size: "40x10" %></li>
        <li><%= f.text_area :body, placeholder: 'Digite seu texto...', size: "45x10" %></li>
        <li style="text-align: center"><%= f.submit 'Enviar' %></li>
    <% end %>
      </ul>

    </div>
  </div>

<div class="return"><a href="/">Voltar à página inicial</a></div>

app/views/layouts/_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_footer.html.erb

<footer>
  <small>© Veg Places Curitiba <%= Time.now.year %> - Todos os direitos reservados</small>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
<nav class="navbar navbar-default navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" id="logo" href="/"><div class="image_tag"><%= image_tag("vegplaces.png", class: "image_tag") %></div></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a class="options" href="/profissionaisvegs">Profissionais Vegs</a></li>
      <li><a class="options2" href="/contato">Contato</a></li>
    </ul>
  </div>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veg Places Curitiba <%= yield(:title) %></title>
    <%= render 'layouts/default' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <div class="center jumbotron">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</div>
  </body>
</html>

app/views/places/_form_tags.html.erb
<div class="col-lg-6" id="search">
  <p>Selecione o tipo de estabelecimento ou serviço desejado:</p>
<%= form_tag places_path, :method => 'get' do %>
  <%= select_tag 'search', options_for_select(["Lanchonete", "Restaurante", "Pizzaria", "Delivery e Encomendas", "Hamburgueria", "Cafeteria", "Confeitaria", "Sorveteria",
  "Produtos Veganos"], params[:search]), prompt: "Selecione um local ou serviço", class: "select" %>
  <%= submit_tag "Procurar", :name => nil, class: "btn btn-md btn-warning" %>
<% end %>
</div>
<div class="col-lg-5 col-lg-offset-1" id="search2">
<p>Ou selecione o bairro ou a cidade de seu interesse:</p>
<%= form_tag places_path, :method => 'get' do %>
  <%= select_tag 'search', options_for_select(["Abranches", "Ahú", "Alto da Rua XV", "Água Verde", "Bacacheri", "Bairro Alto", "Batel", "Boa Vista",
    "Bom Retiro", "Capão da Imbuia", "Centro", "C. Cívico",
    "Hugo Lange", "Jardim Botânico", "Mercês", "Portão", "Rebouças", "São Francisco", "São José dos Pinhais", "Seminário"], params[:search]), prompt: "Selecione um bairro ou cidade", class: "select" %>
  <%= submit_tag "Procurar", :name => nil, class: "btn btn-md btn-warning" %>
<% end %>
</div>

app/views/places/_result.html.erb


<% @places.each do |place| %>

  <% if place.modality != 'Delivery e Encomendas' %>
    <div id="local">
      <div class="row">
        <div class="col-md-8">
          <ul>
            <li id="name"><u><%= place.name %></u><li>
            <li id="jovem"><%= place.modality %></li>
            <li id="jovem">Tipo: <%= place.sort %></li>
            <li id="jovem">Endereço: <%= place.address %></li>
            <li id="jovem">Horário de funcionamento: <%= place.openinghours %></li>
            <li id="jovem"><%= link_to "Página do Facebook", place.facebookpage %></li>
          </ul>
        </div>
        <div class="col-md-4">
          <%= content_tag(:iframe, '', width: 225, height: 150,
          src: "https://www.google.com/maps/embed/v1/place?key=AIzaSyDlQvLpA0mO1hrqRqGzC9Cz2L_Q7n86kHw&q=#{place.name}") %>
        </div>
      </div>
    </div>

  <% else %>
    <div id="local">
      <div class="row">
        <div class="col-md-8">
          <ul>
            <li id="name"><u><%= place.name %></u><li>
            <li id="jovem"><%= place.modality %></li>
            <li id="jovem">Tipo: <%= place.sort %></li>
            <li id="jovem">Localização: <%= place.address %></li>
            <li id="jovem">Horário de funcionamento: <%= place.openinghours %></li>
            <li id="jovem"><%= link_to "Página do Facebook", place.facebookpage %></li>
          </ul>
        </div>
      </div>
    </div>
  <% end %>

<% end %>

app/views/places/edit.html.erb
<%= form_for(@place) do |pl| %>
<ul class="col-md-6">
<li>
<%= pl.label :name, "Nome" %>
<%= pl.text_field :name %></li>

<li><%= pl.label :modality, "Tipo" %>
<%= pl.text_field :modality %></li>

<li><%= pl.label :description, "Descrição" %>
<%= pl.text_field :description %></li>

<li><%= pl.label :openinghours, "Horário" %>
<%= pl.text_field :openinghours %>
</li>
</ul>
<ul class="col-md-6">
<li><%= pl.label :sort, "Espécie" %>
<%= pl.text_field :sort %></li>

<li><%= pl.label :address, "Endereço" %>
<%= pl.text_field :address %></li>

<li><%= pl.label :facebookpage, "Pág Face" %>
<%= pl.text_field :facebookpage %></li>
</ul>

<%= pl.submit "Atualizar Estabelecimento" %>

<% end %>

app/views/places/home.html.erb
<div class="center jumbotron">
  <div class="index">
    <p id="welcome">Bem-vindo ao Veg Places Curitiba e região! Este site conta, até o momento, com <u><%= places_count %></u>
      estabelecimentos vegetarianos e veganos (ou com opções veganas) e <u><%= professionals_count %></u> profissional veg cadastrados.</p>
    <div class="row" id="rowes">

        <%= render 'form_tags' %>

    </div>
  </div>
</div>

app/views/places/index.html.erb
<div class="center jumbotron">
  <div class="index">
    <div class="row" id="rowes">

        <%= render 'form_tags' %>

    </div>

    <h4><%= search_count %></h4>

    <%= render 'result' %>

  </div>
</div>

app/views/places/list.html.erb
<%= link_to "Log out", logout_path, method: :delete %><br/><br/>

<%= form_for(@place) do |pl| %>
<ul class="col-md-6">
<li>
<%= pl.label :name, "Nome" %>
<%= pl.text_field :name %></li>

<li><%= pl.label :modality, "Tipo" %>
<%= pl.text_field :modality %></li>

<li><%= pl.label :description, "Descrição" %>
<%= pl.text_field :description %></li>

<li><%= pl.label :openinghours, "Horário" %>
<%= pl.text_field :openinghours %>
</li>
</ul>
<ul class="col-md-6">
<li><%= pl.label :sort, "Espécie" %>
<%= pl.text_field :sort %></li>

<li><%= pl.label :address, "Endereço" %>
<%= pl.text_field :address %></li>

<li><%= pl.label :facebookpage, "Pág Face" %>
<%= pl.text_field :facebookpage %></li>
</ul>

<%= pl.submit "Criar estabelecimento" %>

<% end %>

<table align="center">
  <tbody>
    <tr>
      <th>Nome</th>
      <th>Tipo</th>
      <th>Descrição</th>
      <th>Horário</th>
      <th>Espécie</th>
      <th>Endereço</th>
      <th>Pág Face</th>
    </tr>
<% @places.each do |place| %>
<tr>
<td><%= place.name %></td>
<td><%= place.modality %></td>
<td><%= place.description %></td>
<td><%= place.openinghours %></td>
<td><%= place.sort %></td>
<td><%= place.address %></td>
<td><%= place.facebookpage %></td>
<td><%= link_to "Edit", edit_place_path(place) %></td>
<td><%= link_to "Delete", place, method: :delete %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/professionals/profs.html.erb
<% provide(:title, "| Profissionais Vegs") %>

<p id="profsvegs">Abaixo estão listados os(as) profissionais veganos(as) cujas áreas de atuação estão relacionadas ao vegetarianismo ou veganismo:</p>

<div class="row">
  <% @professionals.each do |professional| %>

    <div class="col-sm-6">
      <div id="professional">

        <ul>
          <li id="name_professional"><u><%= professional.name %></u></li>
          <li id="jovem_professional"><%= professional.function %></li>
          <li id="jovem_professional">Número: <%= professional.phone_number %></li>
          <li id="jovem_professional">Email: <%= professional.email %></li>
        </ul>
      </div>
    </div>

  <% end %>
</div>


<div class="return"><a href="/">Voltar à página inicial</a></div>